[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  # Add any necessary environment variables here
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"